### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by dorivansousa** [andreiox/sefaz-communicator#8]
eu consigo comunicar com o ws do exemplo no caso da Bahia mas quando mudo a url pra o maranhao (https://hom.sefazvirtual.fazenda.gov.br/NFeStatusServico4/NFeStatusServico4.asmx) recebo esse erro

**Comment by andreiox** [comment]
### Diagnóstico

O certificado do domínio **hom.sefazvirtual.fazenda.gov.br** está inválido.

Diagnosticando o certificado usando [openssl s_client](https://www.openssl.org/docs/man1.0.2/man1/openssl-s_client.html):

```shell
openssl s_client -connect hom.sefazvirtual.fazenda.gov.br:443
```

Temos o seguinte resultado:

```
---
SSL handshake has read 4392 bytes and written 515 bytes
Verification error: unable to get local issuer certificate
---
```

Se tentarmos entrar nele via Firefox, ele acusa a conexão como insegura, dando como motivo:

```text
Owner: This website does not supply ownership information.
```

### Resolução

Você pode setar a variável de ambiente NODE_TLS_REJECT_UNAUTHORIZED como 0 para fazer com que o node desabilite as verificações para conexões SSL. Leia mais sobre esse comando [aqui](https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value).

#### Observação

Setar essa variável como 0 faz com que as conexões SSL se tornem inseguras, porém não conheço outra forma de resolver esse problema.
