### ISSUE TITLE
When a wsdl has multiple ports and bindings, the create Soap method does not find the correct method

### ISSUE THREAD

**Issue by lucaspere** [andreiox/sefaz-communicator#9]
![image](https://user-images.githubusercontent.com/46873546/135631830-5de7e159-c537-423b-bb91-f8c222d90f08.png)
![image](https://user-images.githubusercontent.com/46873546/135632293-a2fb1a67-f2d7-459b-b39b-157bdfbbe958.png)

**Comment by andreiox** [comment]
Fixed in #10
